### ISSUE TITLE
Incorrect conversion of `Timex.now/1` to `DateTime.utc_now/1`

### ISSUE THREAD

**Issue by kerryb** [adobe/elixir-styler#66]
## Versions

* Elixir: 1.15.2 (compiled with Erlang/OTP 26)
* Styler: 0.8.3

## Example Input

```elixir
Timex.now("Europe/London")
```

## Stacktrace / Current Behaviour

Styler converts `Timex.now/1` to `DateTime.utc_now/1`, which expects a calendar or unit (not a timezone). This is the formatted code:

```elixir
DateTime.utc_now("Europe/London")
```

I believe the correct conversion should be:

```elixir
DateTime.now!("Europe/London")
```

**Comment by novaugust** [comment]
:O thanks for the bug report! will have that fixed in a jiffy

**Comment by novaugust** [comment]
fixed on main, will publish a release at the end of the workday =) thanks again for the report (and even moreso for telling me what it _should_ be!)

**Comment by kerryb** [comment]
Thanks for the quick fix!

**Comment by novaugust** [comment]
released v0.8.4, hope this works better across the pond now :)

**Comment by sabiwara** [comment]
Hello! I noticed that this issue is still happening when using the pipe operator:

```elixir
"Europe/London" |> Timex.now() |> dbg()
# becomes
"Europe/London" |> DateTime.utc_now() |> dbg()
```

The [fix](https://github.com/adobe/elixir-styler/commit/9d1a29915b892f1721cd6e0fc56415c95bbd20bf#diff-cb8644f7799ce7b2c71b000253b50ac50e2d4d4959ec2a70aa64ab0ba5bbda57R103) is happening on the node (apparent arity 0), but doesn't account for the effective arity of the call due to the pipe (arity 1).

**Comment by novaugust** [comment]
ahh thank you sabiwara, and apologies for missing that. will get a fix up

**Comment by novaugust** [comment]
published 0.9.5 with fix for the pipes problem. cheers

**Comment by sabiwara** [comment]
Thanks Matt for the fix and for the awesome project! Cheers 💜
